"""Europe — 5 événements internationaux majeurs."""

EUROPE = [
    dict(
        slug="bits-and-pretzels",
        name="BITS & PRETZELS",
        title="LA CONFÉRENCE INTERNATIONALE DE FONDATEURS",
        date="28 au 30 septembre 2026",
        lieu="Munich — Allemagne",
        audience="Fondateurs de startups, scale-ups, investisseurs, VCs, corporate innovation, acteurs tech européens et internationaux.",
        taille="7 500+ participants — écosystème startup européen à forte dimension internationale.",
        format="Keynotes, panels, pitchs startups, networking intensif, side events, rencontres investisseurs.",
        infos="Organisé par Startup Events GmbH. Positionné comme un “Oktoberfest du business”. Audience très internationale (Europe + US + écosystèmes tech globaux).",
        speakers="Max Junestrand (Legora) — Mirko Novakovic (Dash0) — Jeannette Zu Furstenberg (General Catalyst) — Ben Fletcher (Accel) — Ritika Pai (Iconiq).",
        interets=[
            "Renforcer la visibilité du Crédit Agricole à l’échelle européenne sur l’écosystème startup.",
            "Accéder à un dealflow international (scale-ups, early-stage, VCs).",
            "Développer des opportunités de partenariats hors marché français.",
            "Positionner la banque dans les réseaux d’innovation européens.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque européenne ouverte sur les écosystèmes internationaux, capable d’accompagner la croissance et l’expansion des scale-ups en Europe et à l’international.",
        activations=[
            ("Présence networking forte (C-level / innovation)", "dîner ou soirée networking avec VCs et fondateurs européens (notamment de la French Tech)"),
            ("Prise de parole internationale", "financement des scale-ups, expansion européenne, innovation bancaire basée sur l’humain / le fondateur"),
            ("Participer au matchmaking", "rencontres partenaires (fonds, IA, fintech internationales, French Tech Berlin)"),
            ("Contenus social media & brand awareness", None),
        ],
        site="https://www.bitsandpretzels.com/",
    ),
    dict(
        slug="gitex-europe",
        name="GITEX EUROPE",
        title="LE SALON MONDIAL DE LA TECH EN EUROPE",
        date="30 juin au 1er juillet 2026",
        lieu="Berlin — Allemagne",
        audience="Décideurs tech, dirigeants grands groupes, gouvernements, startups, scale-ups, investisseurs, experts IA, cybersécurité et cloud.",
        taille="60 000+ participants — événement tech mondial majeur.",
        format="Global tech expo, conférences, keynotes, démonstrations technologiques, zones startups, networking international.",
        infos="Version européenne de la franchise mondiale GITEX. Focus : IA, cybersécurité, cloud, data, infrastructures numériques, deeptech.",
        speakers="Maya Noel (France Digitale) — Kazuhito Hadano (Sony Ventures) — Ryan Fouty (Perplexity) — Alberto Bacchiega (Commission européenne) — Yannick Marin Isambert (Airbus).",
        interets=[
            "Accéder à un écosystème global (Europe, Middle East, US, Asie).",
            "Renforcer la crédibilité sur l’IA, la cybersécurité et les infrastructures digitales.",
            "Identifier des partenaires technologiques stratégiques à grande échelle.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque européenne connectée aux technologies mondiales, capable d’intégrer et de sécuriser les innovations IA et cyber à grande échelle.",
        activations=[
            ("Prise de parole internationale (C-level)", "IA, cybersécurité, souveraineté technologique, infrastructure bancaire"),
            ("Présence sur zone innovation / expo", "démonstration de cas d’usage IA / data / sécurité"),
            ("Participer aux side events", "dîner, cocktail (souvent organisés par SAP, Microsoft, AWS…)"),
            ("Participer aux Executive Connect", "programme sur invitation reliant dirigeants secteurs régulés et fournisseurs IA"),
        ],
        site="https://www.gitexeurope.com/",
    ),
    dict(
        slug="slush",
        name="SLUSH",
        title="L’ÉVÉNEMENT LE + CENTRÉ SUR LES FONDATEURS, LE PLUS GRAND RASSEMBLEMENT DE CAPITAL-RISQUE",
        date="18 au 19 novembre 2026",
        lieu="Helsinki — Finlande",
        audience="Décideurs tech, fondateurs de startups early stage à scale-ups, fonds d’investissement internationaux, corporate venture.",
        taille="12 000+ participants — très forte concentration VC.",
        format="Keynotes, pitching sessions / startup matchmaking, 1to1 meetings, side events, startup village.",
        infos="Organisé par Slush (association). Événement très “founder-first” (positionnement rare en Europe). Networking ultra ciblé : deals, fundraising, co-investissements.",
        speakers="Anton Osika (Lovable) — Lucy Liu (Airwallex) — Markus Villig (Bolt) — Marc Lemaître (Commission européenne) — Tim Zheng (Apollo.io) — Eileen O’Mara (Stripe).",
        interets=[
            "Opportunité de visibilité auprès des VC internationaux.",
            "Détection de tendances : IA, climate tech, fintech, deeptech.",
            "Accès direct à des startups en levée de fonds (early + growth).",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque européenne connectée aux écosystèmes technologiques mondiaux, capable de financer, structurer et sécuriser la croissance des startups et scale-ups dans l’IA et la fintech.",
        activations=[
            ("Prendre la parole sur une table ronde VC & founders", "format très orienté terrain, partage d’expérience plutôt que représentation institutionnelle"),
            ("Organiser un side event référencé par l’événement", "Exemple : relation banques / fonds / startups dans les tours de financement"),
            ("Contenus social media & brand awareness", None),
        ],
        site="https://slush.org/",
    ),
    dict(
        slug="wave-by-vento",
        name="WAVE BY VENTO",
        title="L’UNE DES CONFÉRENCES TECHNOLOGIQUES LES + INFLUENTES D’ITALIE",
        date="7 au 9 octobre 2026",
        lieu="Turin — Italie",
        audience="Fondateurs, fonds de capital-risque, corporate venture capital, grands groupes tech et infrastructure, acteurs publics et écosystèmes innovation européens, médias tech.",
        taille="15 000+ participants — 1 500 startups et +1 500 investisseurs présents.",
        format="Keynotes, tables rondes, 1to1 (≈ 4 500 meetings), zones de démos, podcast live et contenus éditoriaux.",
        infos="Organisé par Vento Ventures. Anciennement Italian Tech Week, devenu Wave by Vento (rebranding international).",
        speakers="John Elkann (Exor, Stellantis, Ferrari) — Dario Amodei (Anthropic) — Alex Kendall (Wayve) — Anas Biad (Sequoia) — Anne Osdoit (Moon Surgical) — Éléonore Crespo (Pigment) — Joe Tsai (Alibaba).",
        interets=[
            "Renforcement de la visibilité auprès des fonds et corporate venture internationaux.",
            "Opportunité de créer des partenariats VC / corporate / tech à l’échelle européenne.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque européenne connectée aux écosystèmes technologiques mondiaux, capable de dialoguer avec les grandes plateformes, les investisseurs et les startups globales.",
        activations=[
            ("Organiser des meetings multi-cibles (écosystème élargi)", "activation business et stratégie, dans un environnement très international et hybride"),
            ("Sponsoriser la Night Summit", "événements dans toute la ville — opportunité grand public en dehors du site principal"),
            ("Rejoindre le programme des ambassadeurs", "accès privilégié de mise en relation et formats privés (VIP networking, introductions ciblées)"),
        ],
        site="https://wavebyvento.com/",
    ),
    dict(
        slug="web-summit",
        name="WEB SUMMIT",
        title="LE SALON MONDIAL DE LA TECH EN EUROPE",
        date="9 au 12 novembre 2026",
        lieu="Lisbonne — Portugal",
        audience="Décideurs tech, dirigeants grands groupes, gouvernements, startups, scale-ups, investisseurs, médias internationaux, leaders d’opinion tech, écosystème (incubateurs, accélérateurs, hubs).",
        taille="70 000+ participants — événement tech mondial.",
        format="Keynotes, tables rondes multi-thématiques, startup pitch competitions, 1to1 meetings, village partenaires.",
        infos="Mix entre branding, business development et dealflow. Forte présence d’acteurs finance et fintech (Visa, Capital Numbers, Worldline, Payabl., Spendbase, TransactionLink…).",
        speakers="Alex Schultz (Meta) — Khaby Lame — Toto Wolff (Mercedes-AMG F1) — Cristiano Amon (Qualcomm) — A.G. Sulzberger (The New York Times).",
        interets=[
            "Très forte densité de side events privés et corporate activations.",
            "Visibilité mondiale auprès d’un écosystème tech élargi (au-delà du VC pur).",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque européenne connectée aux écosystèmes technologiques mondiaux, capable de dialoguer avec les grandes plateformes, les investisseurs et les startups globales.",
        activations=[
            ("Prendre la parole sur une table ronde avec une fintech européenne", "rôle des banques dans l’accompagnement des scale-ups globales"),
            ("Participer au side event de Mastercard “Fintech & Impact”", None),
            ("Organiser des meetings ciblés (VC, scale-ups et corporate tech)", "générer du dealflow qualifié et renforcer les partenariats stratégiques"),
        ],
        site="https://websummit.com/",
    ),
]
