"""France — 15 events leviers de notoriété & business."""

FRANCE = [
    dict(
        slug="changenow",
        name="CHANGENOW",
        title="LE PLUS GRAND ÉVÉNEMENT DE SOLUTIONS POUR LA PLANÈTE",
        date="26 au 28 avril 2027",
        lieu="Grand Palais, Paris",
        audience="Dirigeants, investisseurs, décideurs publics, startups à impact, ONG, grand public engagé.",
        taille="40 000 participants — 10k entreprises, 1,4k investisseurs, +140 pays représentés.",
        format="Keynotes, conférences, networking, exposition de solutions, pitchs startups, programmes investisseurs, VIP Lunch.",
        infos="Arkea est Major Investor Partner. +500 médias présents. Forte présence corporate (L’Oréal, AXA, Kering…).",
        speakers="Laurent Fabius (Président COP21) — Prince Albert II de Monaco — Thomas Jolly (DA Cérémonies JO Paris 2024) — Lucie Basch (Poppins) — Isabelle Combarel (Arkéa).",
        interets=[
            "10 ans de l’événement en 2027 — édition anniversaire.",
            "Opportunités business : dealflow startups, partenariats impact.",
            "Légitimité sur les sujets ESG / impact investing.",
        ],
        positionnement="Positionner le Crédit Agricole et Transition Énergie comme le partenaire financier de référence des transitions (agricole, énergétique, territoriale), capable de connecter innovation et financement.",
        activations=[
            ("Prise de parole", "keynote / panel sur les transitions et le financement durable"),
            ("Stand expérientiel", "cas concrets financés : agriculture durable, climat, innovation"),
            ("Programme startups / investisseurs", "via La Fabrique by CA — rencontres startups à impact (logique de dealflow)"),
        ],
        site="https://www.changenow.world/fr/",
        highlight="10 ans de l’événement — édition anniversaire 2027",
    ),
    dict(
        slug="raise-summit",
        name="RAISE SUMMIT",
        title="LE SOMMET MONDIAL DE RÉFÉRENCE D’IA",
        date="8 au 9 juillet 2026 (side event le 7 — dîner à Versailles)",
        lieu="Carrousel du Louvre, Paris",
        audience="Dirigeants tech, fondateurs de startups et scale-ups, investisseurs, experts IA/data, grands groupes tech.",
        taille="9 000+ participants — audience internationale.",
        format="Keynotes, panels, networking, side events, rencontres investisseurs/startups.",
        infos="Organisé par Chain of Events. Partenaire bancaire international : Bank of America — absence d’acteurs bancaires français → opportunité de positionnement.",
        speakers="Mark Cuban (MCC) — Yann LeCun (AMI) — Anton Osika (Lovable) — Scott Wu (Cognition) — Jarek Kutylowski (DeepL) — Andrey Khusid (Miro).",
        interets=[
            "Renforcer la crédibilité du Crédit Agricole sur l’innovation, la fintech et l’IA.",
            "Occuper un territoire pas/peu investi par les banques françaises.",
            "Accéder à un dealflow startups / scale-ups à fort potentiel.",
        ],
        positionnement="Positionner le Crédit Agricole comme la banque française qui prend le leadership sur un territoire tech déserté par ses concurrents, seule à capter à la fois les opportunités business et les cercles d’influence les plus exclusifs.",
        activations=[
            ("Prise de parole (tech / business)", None),
            ("Programme startups / investisseurs", "rencontres fintech, IA, scale-ups — sponsoring de Raise the Stakes (compétition IA)"),
            ("Activation contenu", "interviews fondateurs, tendances IA/data, diffusion social media"),
            ("Sponsoriser le side event Versailles", "dîner privé du 7/07 au Château de Versailles"),
        ],
        site="https://www.raisesummit.com/fr",
        highlight="Banques françaises absentes — territoire à conquérir",
    ),
    dict(
        slug="tech-for-future",
        name="TECH FOR FUTURE",
        title="LE GRAND RENDEZ-VOUS DE LA TECH EUROPÉENNE",
        date="14 avril 2026 (date 2027 à confirmer)",
        lieu="Pathé Palace, Paris",
        audience="Startups deeptech, scale-ups, grands groupes, investisseurs, institutions publiques, médias.",
        taille="1 500+ participants — écosystème qualifié innovation & impact.",
        format="Débats, keynotes, pitchs startups, 6 awards → cérémonie, networking.",
        infos="Organisé par La Tribune x BFM Business. Accent éditorial fort sur la souveraineté. Présence BNP Paribas, Bpifrance, Crédit Mutuel Arkéa.",
        speakers="Lauréats 2025 : SeeHaptic, Alternative Innovation, Phagos, OptimPharma, Neuronaix, Miratlas.",
        interets=[
            "Accéder à un écosystème startups + investisseurs qualifiés.",
            "Identifier des opportunités de financement et d’accompagnement startups.",
            "Forte exposition média (BFM / La Tribune).",
        ],
        positionnement="Positionner le Crédit Agricole comme un acteur bancaire moteur de l’innovation utile et de la souveraineté, au service des startups et des technologies à impact.",
        activations=[
            ("Prise de parole innovation / impact", "Exemple 2026 : Financement de la tech, comment rester dans la course ? (avec Philippe Tibi)"),
            ("Participation aux jurys / awards startups", "visibilité forte sur les projets deeptech et impact"),
            ("Stand / démonstration", None),
            ("Contenus éditoriaux", "interviews startups, décryptages tendances tech & green"),
            ("Networking investisseurs / startups", "sourcing et détection de projets early stage"),
        ],
        site="https://techforfuture.fr/",
    ),
    dict(
        slug="aktionnaire-day",
        name="AKTIONNAIRE DAY",
        title="LE + GRAND ÉVÉNEMENT FRANÇAIS DÉDIÉ AUX NOUVEAUX INVESTISSEURS",
        date="21 mars 2026 (édition 2027 à venir)",
        lieu="Station F, Paris",
        audience="Grand public, investisseurs particuliers et institutionnels, fintechs, gestion d’actifs, banques, plateformes d’investissement.",
        taille="4 000+ participants.",
        format="Conférences, keynotes, masterclasses, networking.",
        infos="Organisé par le média Aktionnaire. Forte dimension pédagogie financière (cible : futures générations d’investisseurs). Présence BNP Paribas, Trade Republic, Amundi.",
        speakers="François Villeroy de Galhau (Banque de France) — Jean de la Rochebrochard (Kima Ventures) — Estelle Castres (BlackRock) — Matthias Baccino (Trade Republic) — Frédéric Mazzela (Blablacar) — Jonathan Anguelov (Offstone).",
        interets=[
            "Positionnement hybride : grand public + acteurs experts.",
            "Renforcer la proximité avec les investisseurs particuliers et les nouvelles générations d’épargnants.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque de référence sur la démocratisation de l’investissement, capable d’accompagner toutes les générations dans leurs choix financiers.",
        activations=[
            ("Keynote pédagogie finance", "Exemple 2026 : Est-il possible de combiner investissement responsable et rendement ? (avec Amundi)"),
            ("Présence stand / conseil", "accompagnement personnalisé et mise en avant des solutions d’investissement"),
            ("Contenus social media éducatifs", "formats courts pédagogiques (TikTok / LinkedIn / Instagram)"),
        ],
        site="https://www.aktionnaireday.com/",
    ),
    dict(
        slug="ai-day",
        name="AI DAY",
        title="L’ÉVÉNEMENT INCONTOURNABLE DES LEADERS DE L’IA ET DU NO-CODE",
        date="10 février 2026 (édition 2027 à venir)",
        lieu="Station F, Paris",
        audience="Fondateurs de startups, scale-ups, investisseurs, corporate innovation, experts IA, acteurs du no-code et de la tech européenne.",
        taille="2 000+ participants.",
        format="Keynotes, panels, démos IA/no-code, retours d’expérience, networking, pitchs startups.",
        infos="Organisé par France Digitale et PR[AI]RIE AI. Positionnement très opérationnel (use cases concrets, produits, outils).",
        speakers="Yann LeCun (AMI) — Dominique de Villepin — Octave Klaba (OVHcloud) — Anne Le Hénanff (ministre IA) — Clara Chappaz (ambassadrice IA).",
        interets=[
            "Présence d’acteurs innovation, politiques, investisseurs et grands groupes.",
            "Identifier des solutions activables rapidement dans les métiers du groupe.",
        ],
        positionnement="Positionner le Crédit Agricole comme un acteur bancaire qui intègre et industrialise les outils IA et no-code au service de la transformation métier et de l’efficacité opérationnelle.",
        activations=[
            ("Keynote / retour d’expérience IA", "Exemple 2026 : Runway, Revenue, and Reality — a founder & CFO’s guide to finance in the AI scale-up era (avec Airwallex)"),
            ("Networking innovation", "rencontres avec startups early-stage et scale-ups IA"),
            ("Sponsoriser la workshop area", "via le naming de l’espace"),
        ],
        site="https://ai-day.org/",
    ),
    dict(
        slug="tech-fest-grenoble",
        name="TECH FEST GRENOBLE",
        title="LE SEUL FESTIVAL OÙ SE RETROUVENT INDUSTRIE, RECHERCHE, ÉDUCATION ET ENTREPRENEURIAT",
        date="4 au 6 février 2026 (édition 2027 à venir)",
        lieu="Alpexpo, Grenoble",
        audience="Startups deeptech, chercheurs, industriels, investisseurs, grands groupes, acteurs publics, écosystèmes territoriaux.",
        taille="20 000+ participants — événement tech à forte dimension territoriale et industrielle.",
        format="Conférences et masterclass, jobdating, networking, village innovation.",
        infos="Organisé par Le Dauphiné Libéré x EBRA Group. Positionnement hybride festival + business. Présence Crédit Mutuel, Bpifrance, Le Village by CA.",
        speakers="Guillaume Buffet (Motherbase) — Julien Cadot (Humanoid) — Pascal Descargues (Genoskin) — Laurent Degré (HPE France).",
        interets=[
            "Capitaliser sur la présence existante du Village by CA.",
            "Renforcer la visibilité du Crédit Agricole sur l’innovation deeptech et industrielle.",
        ],
        positionnement="Positionner le Crédit Agricole comme la banque de référence des territoires innovants, capable d’accompagner l’émergence et la croissance des projets deeptech et industriels partout en France.",
        activations=[
            ("Prise de parole territoriale & innovation", "Exemple 2026 : Baromètre économique et financement de la trésorerie pour les TPE, PME et ETI (avec la Banque de France)"),
            ("Activation avec Le Village by CA", "valorisation de l’écosystème startups existant"),
            ("Rencontres startups & industriels", "détection projets et opportunités de financement"),
            ("Contenus média & amplification", "capitaliser sur la puissance éditoriale régionale"),
        ],
        site="https://www.tech-fest.fr/",
    ),
    dict(
        slug="france-digitale-day",
        name="FRANCE DIGITALE DAY",
        title="L’INCONTOURNABLE RÉUNION DE FAMILLE DE LA COMMUNAUTÉ TECH EN FRANCE",
        date="15 septembre 2027",
        lieu="Musée des Arts Forains, Paris",
        audience="Fondateurs de startups, scale-ups, investisseurs (VC, fonds), dirigeants corporate, acteurs publics de l’innovation.",
        taille="4 500+ participants — écosystème tech & investissement très qualifié.",
        format="Tables rondes, déjeuner écosystème, networking, tournages de podcast en live.",
        infos="Organisé par France Digitale. Partenaires : Caisse des Dépôts, Crédit Mutuel Arkéa, Bpifrance, Société Générale, Memo Bank, BNP Paribas.",
        speakers="Philippe Aghion — Gabriel Zucman — Alexia Laroche-Joubert (Banijay) — Thibaut Guilluy (France Travail) — Gary Shapiro (CES) — Roxanne Varza (Station F) — Xavier Lazarus (Elaia).",
        interets=[
            "Développer des relations avec fonds d’investissement et investisseurs.",
            "Être au cœur des acteurs de référence de l’écosystème.",
        ],
        positionnement="Positionner le Crédit Agricole comme un acteur bancaire incontournable du financement des startups et de la croissance des scale-ups en France et en Europe.",
        activations=[
            ("Participation à une table ronde", "visibilité sur les enjeux financement, innovation et croissance"),
            ("Organisation de rendez-vous stratégiques", "rencontres ciblées avec les acteurs incontournables"),
            ("Sponsoring du déjeuner écosystème", "moment clé de networking premium"),
            ("Participation au podcast Feuille Blanche (live)", "prise de parole incarnée + amplification immédiate"),
            ("Activation avec fonds d’investissement", "partenariats, co-financement, visibilité croisée"),
        ],
        site="https://fdday.eu/",
    ),
    dict(
        slug="france-fintech-forum",
        name="FRANCE FINTECH FORUM",
        title="L’ÉVÉNEMENT DE RÉFÉRENCE DE LA FINTECH EN FRANCE",
        date="1er avril 2026 (édition 2027 à venir)",
        lieu="Station F, Paris",
        audience="Acteurs fintech, banques, investisseurs, régulateurs, institutions financières, startups, experts innovation.",
        taille="1 000+ participants — écosystème fintech ultra qualifié.",
        format="Keynotes, tables rondes, workshops, networking, démos solutions.",
        infos="Organisé par France Fintech. Lien direct entre innovation fintech et institutions financières. Présence Crédit Mutuel Arkéa, Bpifrance, Banque de France, Banque Hottinguer.",
        speakers="Stéphane Alizon (Younited) — Alexandre Garabedian (L’Agefi) — Simon Parisot (LCL) — Pierre Marin (Rockfi) — Maevas Courtois (Helios) — Benjamin Chemla (Shares).",
        interets=[
            "Anticiper les mutations du secteur bancaire (régulation, nouveaux usages).",
            "Développer des partenariats avec fintechs et institutions.",
        ],
        positionnement="Positionner le Crédit Agricole comme un acteur bancaire moteur de l’innovation fintech, capable de connecter institutions, startups et nouveaux usages financiers.",
        activations=[
            ("Participation à une table ronde", "Exemple 2026 : Money Talks — How AI Makes Finance Listen (avec Lydia)"),
            ("Organisation de rendez-vous stratégiques", "rencontres avec fintechs clés, régulateurs et partenaires"),
            ("Présence en demo space", "mise en avant de cas d’usage ou collaborations fintech"),
            ("Networking ciblé", "construire un partenariat durable avec France Fintech"),
        ],
        site="https://francefintech.org/fft26/",
    ),
    dict(
        slug="big-bpifrance",
        name="BIG BPIFRANCE",
        title="LE GRAND RASSEMBLEMENT DES ENTREPRENEURS",
        date="8 octobre 2026",
        lieu="Accor Arena (Bercy), Paris",
        audience="Entrepreneurs, startups, dirigeants de PME/ETI, grands groupes, investisseurs, institutions publiques, étudiants, grand public.",
        taille="75 000+ participants — plus grand rassemblement business & innovation d’Europe.",
        format="Keynotes, conférences, ateliers, networking, village partenaires, contenus live.",
        infos="Organisé par Bpifrance. Caisse d’Épargne, La Banque Postale, HSBC, Business France, Banque de France partenaires. Couverture média massive.",
        speakers="Sébastien Bazin (ACCOR) — Patrick Martin (MEDEF) — Slawomir Krupa (Société Générale) — Inoxtag — Laura Chaubard (X).",
        interets=[
            "Toucher une audience massive et diversifiée (PME, startups, grand public).",
            "Couverture média massive (TV, presse, digital).",
        ],
        positionnement="Positionner le Crédit Agricole comme la banque de référence de l’économie réelle et de l’innovation, capable d’accompagner tous les entrepreneurs, de la startup à la PME jusqu’au grand groupe.",
        activations=[
            ("Présence majeure (stand / village partenaire)", "visibilité maximale dans un environnement concurrentiel"),
            ("Multiples prises de parole (dirigeants, experts)", "Exemple 2025 : Financer une reprise d’entreprise — toutes les solutions à votre portée (avec Arkanum)"),
            ("Programme de rendez-vous business", "rencontres avec entrepreneurs, partenaires, institutions"),
            ("Activation média & contenus", "capitaliser sur la couverture presse + production de contenus live"),
        ],
        site="https://big.bpifrance.fr/",
    ),
    dict(
        slug="paris-economic-forum",
        name="PARIS ECONOMIC FORUM",
        title="(EX HUB FORUM) — POUR RÉUNIR LES DIRIGEANTS VISIONNAIRES ET DÉCIDEURS DE 1ER PLAN",
        date="1er au 2 décembre 2026",
        lieu="Paris",
        audience="CEOs de grands groupes et scale-ups, ministres et décideurs publics, investisseurs, experts économiques, think tanks, médias économiques.",
        taille="300+ participants — audience sélectionnée, très qualifiée et internationale.",
        format="Keynotes, tables rondes, débats, format hybride influence + contenu + visibilité.",
        infos="Organisé par Hub Institute. Sous le haut patronage du Président de la République Emmanuel Macron. Forte dimension internationale.",
        speakers="Clara Chappaz (ambassadrice IA) — Philippe d’Ornano (Sisley) — Benoit Derigny (ManpowerGroup) — Nicolas Dufourcq (Bpifrance) — Enrique Martinez (Fnac-Darty).",
        interets=[
            "Cercle de décideurs économiques et politiques de premier plan.",
            "Forte dimension internationale malgré un ancrage parisien.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque européenne pleinement intégrée aux cercles de décision économiques et politiques, capable de connecter dirigeants, fondateurs et pouvoirs publics autour des grandes transformations de l’économie.",
        activations=[
            ("Prendre la parole en keynote ou session plénière", "intervention d’un dirigeant CA sur les grandes transformations économiques et financières"),
            ("Valoriser la présence via les contenus digitaux et la diffusion du forum", "renforcement de la marque sur les sujets de transformation économique et innovation"),
        ],
        site="https://www.pariseconomicforum.com/",
    ),
    dict(
        slug="adopt-ai",
        name="ADOPT AI",
        title="LE GRAND RENDEZ-VOUS EUROPÉEN DÉDIÉ À L’IA",
        date="3 au 4 décembre 2026",
        lieu="Grand Palais, Paris",
        audience="Dirigeants (C-level), décideurs data/IA, responsables innovation, grands groupes, scale-ups tech.",
        taille="20 000+ participants — audience ultra qualifiée, orientée décideurs.",
        format="Keynotes, retours d’expérience, cas clients, workshops, networking, stands démos.",
        infos="Organisé par Artefact. Positionné comme le “Davos de l’IA”. Partenaires sponsors : Société Générale, BPCE.",
        speakers="Olivier Gavalda speaker en 2025.",
        interets=[
            "Créer des opportunités de collaboration avec des acteurs tech et data.",
            "Audience décideurs sur les enjeux d’industrialisation IA.",
        ],
        positionnement="Positionner le Crédit Agricole comme une institution financière qui industrialise l’IA à grande échelle.",
        activations=[
            ("Networking stratégique", "rencontres ciblées avec décideurs IA / innovation"),
            ("Keynote premium (niveau C-level)", "capitaliser sur la prise de parole type Olivier Gavalda"),
            ("Sponsoring du déjeuner écosystème", None),
        ],
        site="https://adoptai.artefact.com/",
        highlight="Le “Davos de l’IA”",
    ),
    dict(
        slug="la-ref",
        name="LA REF",
        title="LA RENCONTRE DES ENTREPRENEURS DE FRANCE",
        date="26 au 27 août 2026",
        lieu="Roland Garros, Paris",
        audience="Dirigeants d’entreprises, décideurs publics, politiques, institutions, fédérations, médias.",
        taille="13 000+ participants — audience ultra qualifiée, orientée dirigeants.",
        format="Keynotes, débats, tables rondes, interviews, networking, village partenaires.",
        infos="Organisée par le MEDEF. Le rendez-vous économique et politique de la rentrée en France. +25 médias partenaires en 2025.",
        interets=[
            "Forte présence de personnalités politiques et dirigeants majeurs.",
            "Couverture média massive (TV, presse, digital).",
        ],
        positionnement="Positionner le Crédit Agricole comme un acteur clé de la souveraineté économique et des transformations des territoires, capable de faire le lien entre économie réelle, innovation et politiques publiques.",
        activations=[
            ("Prise de parole stratégique (niveau COMEX)", "sujets : souveraineté économique, financement des entreprises, IA, transition"),
            ("Présence visible dans le village partenaires", "stand orienté influence + rencontres institutionnelles"),
            ("Rencontres ciblées (public / privé)", None),
            ("Activation RP & média", "interviews, tribunes, production de contenus"),
        ],
        site="https://laref.org/",
    ),
    dict(
        slug="bank-acceleration",
        name="BANK ACCELERATION",
        title="LES FORCES QUI TRANSFORMENT L’INDUSTRIE BANCAIRE",
        date="6 octobre 2026",
        lieu="Palais Brongniart, Paris",
        audience="Décideurs bancaires, dirigeants financiers, experts innovation, fintechs, régulateurs, acteurs cybersécurité et blockchain.",
        taille="1 000+ participants.",
        format="Conférences, keynotes, tables rondes, retours d’expérience, débats stratégiques.",
        infos="Organisé par L’Agefi. Thématiques : agents IA, nouveaux services bancaires, agence de demain, euro numérique, blockchain, cybersécurité. Peu de partenaires aujourd’hui.",
        interets=[
            "Prendre part aux débats structurants du secteur (IA, monnaie digitale, infrastructure bancaire).",
            "Renforcer la crédibilité auprès des pairs bancaires et régulateurs.",
            "Anticiper les ruptures technologiques du secteur financier.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque qui anticipe et construit les modèles bancaires de demain, à la croisée de l’IA, de la régulation et de l’innovation technologique.",
        activations=[
            ("Prise de parole stratégique (C-level / direction innovation)", "« La banque augmentée : entre IA, souveraineté et nouveaux usages »"),
            ("Intervention sur cas concrets", "agents IA, automatisation bancaire, transformation des agences"),
            ("Contenus experts & décryptages", "thought leadership sur les transformations du secteur"),
            ("Networking institutionnel", "échanges avec régulateurs, banques et acteurs de place"),
        ],
        site="https://bankacceleration.evenements.agefi.fr/fr/",
        highlight="Peu de partenaires — opportunité de positionnement",
    ),
    dict(
        slug="hubtalk-banking-assurance",
        name="HUB TALK BANQUE & ASSURANCE",
        title="FAIRE DE L’IA UN MOTEUR D’AGILITÉ DANS LE SECTEUR",
        date="5 novembre 2026",
        lieu="Deskeo Champerret, Paris",
        audience="Dirigeants banque & assurance, responsables innovation, data/IA, digital, expérience client, risk & compliance, fintechs et insurtechs.",
        taille="500+ participants — audience qualifiée, très décisionnelle.",
        format="Keynotes, témoignages dirigeants, sessions d’échanges en petits groupes.",
        infos="Organisé par Hub Institute. Thématiques : agilité des organisations, industrialisation de l’IA, personnalisation client, cybersécurité, AI Act.",
        interets=[
            "Travailler la crédibilité sur les sujets de confiance, sécurité et conformité.",
            "Se connecter aux enjeux opérationnels banque & assurance.",
            "Identifier des leviers d’industrialisation rapide de l’IA.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque qui industrialise l’IA de manière responsable, en conciliant performance opérationnelle, personnalisation client et exigences de confiance.",
        activations=[
            ("Témoignage dirigeant / retour d’expérience", "transformation IA dans les métiers banque/assurance"),
            ("Networking expert", "échanges avec décideurs métiers et innovation"),
        ],
        site="https://www.hubinstitute.com/hubtalk/banking-assurance",
    ),
    dict(
        slug="investir-day",
        name="INVESTIR DAY",
        title="LE GRAND RENDEZ-VOUS DE L’ÉPARGNE ET DU PATRIMOINE",
        date="24 novembre 2026",
        lieu="Carrousel du Louvre, Paris",
        audience="Investisseurs particuliers, professionnels de la finance, gestionnaires de patrimoine, fintechs, banques, sociétés de gestion, acteurs crypto et immobilier.",
        taille="8 000+ participants — audience mixte grand public + experts finance.",
        format="Conférences, masterclasses, keynotes, ateliers pédagogiques, networking, espaces exposants.",
        infos="Organisé par Groupe Les Echos-Le Parisien x Hopscotch. Thématiques : crypto, fintech, crowdfunding, investissement responsable, capital investissement, immobilier, fiscalité, bourse, gestion de patrimoine.",
        interets=[
            "Positionnement hybride : expertise + démocratisation.",
            "Capter les évolutions des usages d’investissement (crypto, fintech, …).",
            "Valoriser l’accompagnement patrimonial et la gestion de l’épargne.",
            "Visibilité dans un écosystème grand public à forte audience média.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque de référence sur l’accompagnement patrimonial global, capable de guider les investisseurs dans la complexité des nouveaux marchés financiers.",
        activations=[
            ("Keynote pédagogie investissement", None),
            ("Stand conseil / expertise", "accompagnement personnalisé sur les stratégies d’investissement"),
            ("Contenus éducatifs média", "formats courts pédagogiques (épargne, marchés, IA financière, crypto)"),
        ],
        site="https://www.investirday.fr/",
    ),
]
