"""Influence — 5 cercles fermés et formats d'influence."""

INFLUENCE = [
    dict(
        slug="royaumont",
        name="LES ENTRETIENS DE ROYAUMONT",
        title="LE CERCLE D’INFLUENCE DES DÉCIDEURS ÉCONOMIQUES, POLITIQUES ET INTELLECTUELS",
        date="Édition 2026 (dates à confirmer — généralement en automne)",
        lieu="Abbaye de Royaumont",
        audience="Dirigeants de grandes entreprises françaises et européennes, banquiers et acteurs financiers institutionnels, décideurs publics, hauts fonctionnaires, intellectuels, chercheurs, économistes, journalistes et éditorialistes influents.",
        taille="Format très restreint et sélectif (cercle fermé).",
        format="Tables rondes de haut niveau (économie, géopolitique, société), débats fermés entre dirigeants et experts, dîners et networking informels.",
        infos="Positionnement historiquement très institutionnel et élitiste. BNP Paribas est partenaire.",
        interets=[
            "Peu d’activation visible : logique de discrétion et de légitimité.",
            "Accès aux réflexions structurantes sur les transformations économiques et géopolitiques.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque systémique européenne pleinement intégrée aux cercles de réflexion et de décision économiques et politiques, capable de contribuer aux grands débats structurants.",
        activations=[
            ("Intégrer le cercle des partenaires institutionnels", "objectif d’inscription du Crédit Agricole dans le cercle fermé des partenaires"),
            ("Participer aux dîners et sessions fermées de haut niveau", "accès aux formats les plus exclusifs (dîners, tables rondes restreintes, échanges off)"),
            ("Prendre part aux tables rondes stratégiques", "intervention ciblée sur les transformations économiques, financières ou géopolitiques"),
        ],
        site="https://www.lesentretiens.com/",
        highlight="Cercle fermé — logique de légitimité long terme",
    ),
    dict(
        slug="cercle-giverny",
        name="LE CERCLE DE GIVERNY",
        title="LE RENDEZ-VOUS DES ENTREPRISES DURABLES ET DE LA RSE STRATÉGIQUE",
        date="4 septembre 2026",
        lieu="Musée des impressionnismes, Giverny",
        audience="Dirigeants de grandes entreprises (CAC 40, ETI, multinationales), banques et acteurs financiers institutionnels, décideurs publics, experts RSE, climat, énergie, biodiversité, ONG, chercheurs.",
        taille="1 000+ participants — événement très sélectif et qualifié, orienté cercle de décideurs.",
        format="Tables rondes, keynotes, networking, publication de propositions annuelles issues des travaux du Cercle.",
        infos="Fort ancrage institutionnel (haut patronage du ministère de l’Économie). BNP Paribas et Caisse des Dépôts sont partenaires.",
        interets=[
            "Accéder aux décideurs ESG des grands groupes et aux directions RSE / stratégie.",
            "S’intégrer aux cercles de décision RSE et climat des grandes entreprises françaises et européennes.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque européenne systémique pleinement intégrée aux cercles de décision de la transition, et acteur clé de la convergence entre finance, industrie et politiques publiques.",
        activations=[
            ("Participer aux tables rondes RSE, climat et finance durable", "interventions sur les grands enjeux de transformation économique face à l’urgence climatique"),
            ("S’inscrire dans les groupes de propositions du Cercle de Giverny", "contribution aux travaux annuels produisant des propositions concrètes de transformation"),
        ],
        site="https://cercle-giverny.fr/",
    ),
    dict(
        slug="matins-hec",
        name="LES MATINS HEC",
        title="LE RENDEZ-VOUS INTIMISTE DES DÉCIDEURS ÉCONOMIQUES ET POLITIQUES",
        date="Format récurrent — prochaine édition à programmer selon calendrier 2026",
        lieu="HEC Paris et lieux partenaires (ex : Place Vendôme, salons privés)",
        audience="Alumni HEC et grand public via diffusion social media.",
        taille="Entre 150 et 200 invités par session.",
        format="Interview animée par un journaliste, lors d’un petit-déjeuner.",
        infos="Format historique de la communauté HEC, relancé comme un cercle de réflexion régulier. Exemple récent : Marie-Anne Barbat-Layani (Présidente AMF). Partenariat éditorial avec Challenges.",
        interets=[
            "Contribuer aux débats structurants sur la régulation financière, l’innovation bancaire et la stabilité du système économique.",
            "Lien direct avec les futurs leaders économiques de demain.",
        ],
        positionnement="Positionner le Crédit Agricole en lien direct avec les futurs décideurs économiques de demain, capable de contribuer aux débats structurants sur les transformations du système financier.",
        activations=[
            ("Participer comme invité intervenant (CEO / direction générale / affaires publiques)", "intervention sur les grands enjeux de transformation du secteur bancaire et financier"),
            ("Accéder au cercle d’invitation régulier des décideurs", "influence continue dans la durée"),
        ],
        site="https://hecstories.fr/fr/category/editos/matin-hec/",
    ),
    dict(
        slug="polytechnique-ax",
        name="RENCONTRES ALUMNI POLYTECHNIQUE",
        title="LE RÉSEAU D’INFLUENCE DES INGÉNIEURS ET DÉCIDEURS DE L’INNOVATION",
        date="Programmation continue (événements tout au long de l’année 2026 via le réseau AX)",
        lieu="AX — Association des anciens élèves de l’École polytechnique, Paris et lieux partenaires",
        audience="Alumni X (ingénieurs, chercheurs, entrepreneurs), fondateurs de startups deeptech, IA, cybersécurité, quantique.",
        taille="Audience entre 50 et 300 participants selon les événements.",
        format="Interview classique ou dîner networking alumni.",
        infos="Connexion forte entre recherche scientifique, innovation et pouvoir économique.",
        interets=[
            "Accès direct à un vivier d’ingénieurs, entrepreneurs et décideurs technologiques.",
            "Relation long terme avec les futurs décideurs économiques et industriels européens.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque européenne connectée aux réseaux d’excellence scientifique et technologique, en lien direct avec les futurs décideurs économiques et industriels, capable d’accompagner la transformation des innovations deeptech en projets structurants.",
        activations=[
            ("Prendre part aux conférences et tables rondes thématiques", "interventions sur les enjeux d’innovation technologique et de financement de la deeptech"),
            ("Participer aux dîners et formats alumni à forte valeur relationnelle", "moments de networking très qualifiés avec ingénieurs, entrepreneurs et dirigeants industriels"),
        ],
        site="https://ax.polytechnique.org/fr/agenda",
    ),
    dict(
        slug="challenges-100",
        name="LES 100 STARTUPS OÙ INVESTIR",
        title="LE CLASSEMENT ET L’ÉVÉNEMENT",
        date="Édition 2026 — publication annuelle (généralement en mars)",
        lieu="Événement de reveal à Paris",
        audience="Fondateurs de startups françaises, investisseurs, grands groupes, décideurs économiques et médias spécialisés.",
        taille="100 startups sélectionnées chaque année — forte audience B2B via la publication Challenges, large diffusion auprès des professionnels tech et finance.",
        format="Publication d’un classement éditorial de référence, pitchs et rencontres startups / investisseurs, sessions de networking, valorisation médiatique forte via Challenges.",
        infos="Alumni du classement devenus leaders européens et mondiaux : Doctolib, Back Market, Qonto, etc.",
        interets=[
            "Outil de veille stratégique pour anticiper les futures licornes.",
            "Renforcement du rôle du Crédit Agricole dans le financement de l’innovation en France.",
        ],
        positionnement="Positionner le Crédit Agricole comme une banque européenne ancrée dans le financement de la nouvelle génération d’entrepreneurs, capable d’accompagner les startups les plus prometteuses dès leurs premières phases de croissance.",
        activations=[
            ("Faire partie du jury de sélection", "intégration au comité d’évaluation des 100 startups sélectionnées"),
            ("Prendre la parole en tant que sponsor lors du reveal (keynote)", "enjeux de financement de l’innovation et de passage à l’échelle"),
            ("Proposer une dotation aux lauréats", "prix ou accompagnement dédié (financement, mentoring, accès réseau)"),
        ],
        site="https://www.challenges.fr/classements/start-up/",
    ),
]
