# Structured data extracted from the original deck.
# Each event entry: { "title": str (top tagline), "name": str (event name, optional),
#   "section": "fr"|"eu"|"influence",
#   "date": str, "lieu": str,
#   "audience": str, "taille": str, "format": str, "infos": str,
#   "interets": list[str],
#   "positionnement": str,
#   "activations": list[(str, str|None)]  # bullet title, optional sub
#   "site": str,
#   "highlight": str (note basse) }

EVENTS = [
    # --- FRANCE ---
    {
        "section": "fr",
        "slug": "changenow",
        "title": "LE PLUS GRAND ÉVÉNEMENT DE SOLUTIONS POUR LA PLANÈTE",
        "name": "ChangeNOW",
        "date": "26 au 28 avril 2027",
        "lieu": "Grand Palais, Paris",
        "audience": "Dirigeants d'entreprises, investisseurs, décideurs publics, startups à impact, ONG, grand public engagé.",
        "taille": "40 000 participants — 10k entreprises, 1,4k investisseurs, +140 pays représentés.",
        "format": "Keynotes, conférences, networking, exposition de solutions, pitchs startups, programmes investisseurs, VIP Lunch.",
        "infos": "Arkéa est Major Investor Partner. 10 ans de l'événement → édition anniversaire.",
        "speakers": "Laurent Fabius (Président COP21), Prince Albert II de Monaco, Thomas Jolly (DA Cérémonies JO Paris 2024), Lucie Basch (Poppins), Isabelle Combarel (ARKEA).",
        "interets": [
            "+500 médias présents",
            "Forte présence d'acteurs corporate (L'Oréal, AXA, Kering…)",
            "Opportunités business : dealflow startups, partenariats impact",
            "Légitimité sur les sujets ESG / impact investing",
        ],
        "positionnement": "Positionner le Crédit Agricole et Transition Énergie comme le partenaire financier de référence des transitions (agricole, énergétique, territoriale), capable de connecter innovation et financement.",
        "activations": [
            ("Prise de parole", "keynote / panel"),
            ("Stand expérientiel", "cas concrets financés (agriculture durable, climat, innovation)"),
            ("Programme startups / investisseurs via La Fabrique by CA", "sessions de rencontres avec startups à impact (logique de dealflow)"),
        ],
        "site": "https://www.changenow.world/fr/",
        "highlight": "Édition anniversaire 10 ans · Arkéa Major Investor Partner",
    },
    {
        "section": "fr",
        "slug": "raise-summit",
        "title": "LE SOMMET MONDIAL DE RÉFÉRENCE DE L'IA",
        "name": "RAISE Summit",
        "date": "8 au 9 juillet 2026",
        "lieu": "Carrousel du Louvre, Paris",
        "audience": "Dirigeants tech, fondateurs de startups et scale-ups, investisseurs, experts IA/data, grands groupes tech.",
        "taille": "9 000+ participants — audience internationale.",
        "format": "Keynotes, panels, networking, side events, rencontres investisseurs/startups. Side event 7 juillet — dîner à Versailles.",
        "infos": "Organisé par Chain of Events. Partenaire bancaire international : Bank of America.",
        "speakers": "Mark Cuban (MCC), Yann LeCun (AMI), Anton Osika (Lovable), Scott Wu (Cognition), Jarek Kutyłowski (DeepL), Andrey Khusid (Miro).",
        "interets": [
            "Renforcer la crédibilité du Crédit Agricole sur innovation, fintech & IA",
            "Occuper un territoire pas/peu investi par les banques françaises",
            "Créer des opportunités de partenariats avec acteurs internationaux",
            "Accéder à un dealflow startups / scale-ups à fort potentiel",
        ],
        "positionnement": "Positionner le Crédit Agricole comme la banque française qui prend le leadership sur un territoire tech déserté par ses concurrents, seule à capter à la fois les opportunités business et les cercles d'influence les plus exclusifs.",
        "activations": [
            ("Prise de parole tech / business", None),
            ("Présence stand", None),
            ("Programme startups / investisseurs", "rencontres ciblées (fintech, IA, scale-ups)"),
            ("Sponsoriser Raise the Stakes", "compétition de startups IA"),
            ("Activation contenu", "interviews fondateurs, tendances IA/data, diffusion social media"),
            ("Sponsoriser un side event ou le dîner privé", "Château de Versailles, 7 juillet"),
        ],
        "site": "https://www.raisesummit.com/fr",
        "highlight": "Absence d'acteurs bancaires français → opportunité stratégique majeure",
    },
    {
        "section": "fr",
        "slug": "tech-for-future",
        "title": "LE GRAND RENDEZ-VOUS DE LA TECH EUROPÉENNE",
        "name": "Tech for Future",
        "date": "14 avril 2026 (date 2027 à venir)",
        "lieu": "Pathé Palace, Paris",
        "audience": "Startups deeptech, scale-ups, grands groupes, investisseurs, institutions publiques, médias.",
        "taille": "1 500+ participants — écosystème qualifié innovation & impact.",
        "format": "Débats, keynotes, pitchs startups, 6 awards → cérémonie, networking.",
        "infos": "Organisé par La Tribune × BFM Business. Accent éditorial fort sur la souveraineté.",
        "speakers": "Lauréats 2025 : SeeHaptic, Alternative Innovation, Phagos, OptimPharma, Neuronaix, Miratlas.",
        "interets": [
            "Accéder à un écosystème startups + investisseurs qualifiés",
            "Identifier des opportunités de financement et d'accompagnement startups",
            "Présence concurrente : BNP Paribas, Bpifrance, Crédit Mutuel Arkéa",
        ],
        "positionnement": "Positionner le Crédit Agricole comme un acteur bancaire moteur de l'innovation utile et de la souveraineté, au service des startups et des technologies à impact.",
        "activations": [
            ("Prise de parole innovation / impact", "ex. 2026 : Financement de la tech, comment rester dans la course ? (avec Philippe Tibi)"),
            ("Participation aux jurys / awards startups", "visibilité forte sur les projets deeptech et impact"),
            ("Stand / démonstration", None),
            ("Contenus éditoriaux", "interviews startups, décryptages tendances tech & green"),
            ("Networking investisseurs / startups", "sourcing et détection de projets early stage"),
        ],
        "site": "https://techforfuture.fr/",
        "highlight": "Forte exposition média BFM / La Tribune",
    },
    {
        "section": "fr",
        "slug": "aktionnaire-day",
        "title": "LE PLUS GRAND ÉVÉNEMENT FRANÇAIS DÉDIÉ AUX NOUVEAUX INVESTISSEURS",
        "name": "Aktionnaire Day",
        "date": "21 mars 2026 (date 2027 à venir)",
        "lieu": "Station F, Paris",
        "audience": "Grand public, investisseurs particuliers et institutionnels, fintechs, gestion d'actifs, banques, plateformes d'investissement.",
        "taille": "4 000+ participants.",
        "format": "Conférences, keynotes, masterclasses, networking.",
        "infos": "Organisé par le média Aktionnaire. Positionnement hybride : grand public + acteurs experts.",
        "speakers": "François Villeroy de Galhau (Banque de France), Jean de la Rochebrochard (Kima Ventures), Estelle Castres (BlackRock), Matthias Baccino (Trade Republic), Frédéric Mazzela (Blablacar), Jonathan Anguelov (Offstone).",
        "interets": [
            "Présence d'acteurs majeurs : BNP Paribas, Trade Republic, Amundi",
            "Renforcer la proximité avec investisseurs particuliers et nouvelles générations d'épargnants",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque de référence sur la démocratisation de l'investissement, capable d'accompagner toutes les générations dans leurs choix financiers.",
        "activations": [
            ("Keynote pédagogie finance", "ex. 2026 : Combiner investissement responsable et rendement ? (avec Amundi)"),
            ("Présence stand / conseil", "accompagnement personnalisé, solutions d'investissement"),
            ("Contenus social media éducatifs", "formats courts pédagogiques (TikTok / LinkedIn / Instagram)"),
        ],
        "site": "https://www.aktionnaireday.com/",
        "highlight": "Forte dimension pédagogie financière — cible : futures générations d'investisseurs",
    },
    {
        "section": "fr",
        "slug": "ai-day",
        "title": "L'ÉVÉNEMENT INCONTOURNABLE DES LEADERS DE L'IA ET DU NO-CODE",
        "name": "AI Day",
        "date": "10 février 2026 (date 2027 à venir)",
        "lieu": "Station F, Paris",
        "audience": "Fondateurs de startups, scale-ups, investisseurs, corporate innovation, experts IA, acteurs no-code et tech européenne.",
        "taille": "2 000+ participants.",
        "format": "Keynotes, panels, démos IA/no-code, retours d'expérience, networking, pitchs startups.",
        "infos": "Organisé par France Digitale et PR[AI]RIE AI. Positionnement très opérationnel (use cases concrets, produits, outils).",
        "speakers": "Yann LeCun (AMI), Dominique de Villepin, Octave Klaba (OVHcloud), Anne Le Hénanff (ministre IA), Clara Chappaz (ambassadrice IA).",
        "interets": [
            "Identifier des solutions activables rapidement dans les métiers du groupe",
            "Présence acteurs innovation, politiques, investisseurs et grands groupes",
        ],
        "positionnement": "Positionner le Crédit Agricole comme un acteur bancaire qui intègre et industrialise les outils IA et no-code au service de la transformation métier et de l'efficacité opérationnelle.",
        "activations": [
            ("Keynote / retour d'expérience IA", "ex. 2026 : Runway, Revenue, and Reality — a founder & CFO's guide to finance in the AI scale-up era (avec Airwallex)"),
            ("Networking innovation", "rencontres avec startups early-stage et scale-ups IA"),
            ("Sponsoriser la workshop area", "via le naming de l'espace"),
        ],
        "site": "https://ai-day.org/",
        "highlight": "Solutions IA / no-code activables rapidement dans les métiers",
    },
    {
        "section": "fr",
        "slug": "tech-fest-grenoble",
        "title": "SEUL FESTIVAL OÙ SE RETROUVENT INDUSTRIE, RECHERCHE, ÉDUCATION ET ENTREPRENEURIAT",
        "name": "Tech Fest Grenoble",
        "date": "4 au 6 février 2026 (date 2027 à venir)",
        "lieu": "Alexpo, Grenoble",
        "audience": "Startups deeptech, chercheurs, industriels, investisseurs, grands groupes, acteurs publics, écosystèmes territoriaux.",
        "taille": "20 000+ participants — forte dimension territoriale et industrielle.",
        "format": "Conférences et masterclass, jobdating, networking, village innovation.",
        "infos": "Organisé par Le Dauphiné Libéré × EBRA Group. Positionnement hybride : festival + business. Présence Crédit Mutuel, Bpifrance, Le Village by CA.",
        "speakers": "Guillaume Buffet (Motherbase), Julien Cadot (Humanoid), Pascal Descargues (Genoskin), Laurent Degré (HPE France).",
        "interets": [
            "Capitaliser sur la présence existante du Village by CA",
            "Renforcer la visibilité du Crédit Agricole sur l'innovation deeptech et industrielle",
        ],
        "positionnement": "Positionner le Crédit Agricole comme la banque de référence des territoires innovants, capable d'accompagner l'émergence et la croissance des projets deeptech et industriels partout en France.",
        "activations": [
            ("Prise de parole territoriale & innovation", "ex. 2026 : Baromètre économique et financement de la trésorerie pour TPE, PME et ETI (avec la Banque de France)"),
            ("Activation avec Le Village by CA", "valorisation de l'écosystème startups déjà existant"),
            ("Rencontres startups & industriels", "détection projets et opportunités de financement"),
            ("Contenus média & amplification", "capitaliser sur la puissance éditoriale régionale"),
        ],
        "site": "https://www.tech-fest.fr/",
        "highlight": "Présence existante du Village by CA — levier d'activation direct",
    },
    {
        "section": "fr",
        "slug": "france-digitale-day",
        "title": "L'INCONTOURNABLE RÉUNION DE FAMILLE DE LA COMMUNAUTÉ TECH EN FRANCE",
        "name": "France Digitale Day",
        "date": "15 février 2027",
        "lieu": "Musée des arts forains, Paris",
        "audience": "Fondateurs de startups, scale-ups, investisseurs (VC, fonds), dirigeants corporate, acteurs publics de l'innovation.",
        "taille": "4 500+ participants — écosystème tech & investissement très qualifié.",
        "format": "Tables rondes, déjeuner écosystème, networking, tournages de podcast en live.",
        "infos": "Organisé par France Digitale. Partenaires : Caisse des Dépôts, Crédit Mutuel Arkéa, Bpifrance, Société Générale, Memo Bank, BNP Paribas.",
        "speakers": "Philippe Aghion, Gabriel Zucman, Alexia Laroche-Joubert (Banijay), Thibaut Guilluy (France Travail), Gary Shapiro (CES), Roxanne Varza (Station F), Xavier Lazarus (Elaia).",
        "interets": [
            "Développer des relations avec fonds d'investissement et investisseurs",
            "Être au cœur des acteurs de référence de l'écosystème",
        ],
        "positionnement": "Positionner le Crédit Agricole comme un acteur bancaire incontournable du financement des startups et de la croissance des scale-ups en France et en Europe.",
        "activations": [
            ("Participation à une table ronde", "enjeux financement, innovation et croissance"),
            ("Organisation de rendez-vous stratégiques", "rencontres ciblées avec acteurs incontournables"),
            ("Participation / sponsoring du déjeuner écosystème", "moment clé de networking premium"),
            ("Participation au podcast Feuille Blanche (live)", "prise de parole incarnée + amplification immédiate"),
            ("Présence visible (stand / sponsoring)", None),
            ("Activation avec fonds d'investissement", "partenariats, co-financement, visibilité croisée"),
        ],
        "site": "https://fdday.eu/",
        "highlight": "Terrain concurrentiel fort — Caisse des Dépôts, Arkéa, Bpifrance, SocGen, BNPP",
    },
    {
        "section": "fr",
        "slug": "france-fintech-forum",
        "title": "L'ÉVÉNEMENT DE RÉFÉRENCE DE LA FINTECH EN FRANCE",
        "name": "France Fintech Forum",
        "date": "1er avril 2026 (date 2027 à venir)",
        "lieu": "Station F, Paris",
        "audience": "Acteurs fintech, banques, investisseurs, régulateurs, institutions financières, startups, experts innovation.",
        "taille": "1 000+ participants — écosystème fintech ultra qualifié.",
        "format": "Keynotes, tables rondes, workshops, networking, démos solutions.",
        "infos": "Organisé par France Fintech. Présence Crédit Mutuel Arkéa, Bpifrance, Banque de France, Banque Hottinguer.",
        "speakers": "Stéphane Alizon (Younited), Alexandre Garabedian (L'Agefi), Simon Parisot (LCL), Pierre Marin (Rockfi), Maevas Courtois (Helios), Benjamin Chemla (Shares).",
        "interets": [
            "Anticiper les mutations du secteur bancaire (régulation, nouveaux usages)",
            "Développer des partenariats avec fintechs et institutions",
        ],
        "positionnement": "Positionner le Crédit Agricole comme un acteur bancaire moteur de l'innovation fintech, capable de connecter institutions, startups et nouveaux usages financiers.",
        "activations": [
            ("Participation à une table ronde", "ex. 2026 : Money Talks — How AI Makes Finance Listen (avec Lydia)"),
            ("Organisation de rendez-vous stratégiques", "rencontres avec fintechs clés, régulateurs et partenaires"),
            ("Présence en demo space", "cas d'usage ou collaborations fintech"),
            ("Networking ciblé", "construire un partenariat durable avec France Fintech"),
        ],
        "site": "https://francefintech.org/fft26/",
        "highlight": "Lien direct innovation fintech ↔ institutions financières",
    },
    {
        "section": "fr",
        "slug": "big-bpifrance",
        "title": "LE GRAND RASSEMBLEMENT DES ENTREPRENEURS",
        "name": "Bpifrance Inno Génération (BIG)",
        "date": "8 octobre 2026",
        "lieu": "Accor Arena (Bercy), Paris",
        "audience": "Entrepreneurs, startups, dirigeants PME/ETI, grands groupes, investisseurs, institutions publiques, étudiants, grand public.",
        "taille": "75 000+ participants — plus grand rassemblement business & innovation d'Europe.",
        "format": "Keynotes, conférences, ateliers, networking, village partenaires, contenus live.",
        "infos": "Organisé par Bpifrance. Partenaires : Caisse d'Épargne, La Banque Postale, HSBC, Business France, Banque de France.",
        "speakers": "Sébastien Bazin (ACCOR), Patrick Martin (MEDEF), Slawomir Krupa (SocGen), Inoxtag, Laura Chaubard (Polytechnique).",
        "interets": [
            "Couverture média massive (TV, presse, digital)",
            "Toucher une audience massive et diversifiée (PME, startups, grand public)",
        ],
        "positionnement": "Positionner le Crédit Agricole comme la banque de référence de l'économie réelle et de l'innovation, capable d'accompagner tous les entrepreneurs, de la startup à la PME jusqu'au grand groupe.",
        "activations": [
            ("Présence majeure (stand / village partenaire)", "visibilité maximale dans un environnement concurrentiel"),
            ("Multiples prises de parole (dirigeants, experts)", "ex. 2025 : Financer une reprise d'entreprise (avec Arkanum)"),
            ("Programme de rendez-vous business", "rencontres entrepreneurs, partenaires, institutions"),
            ("Activation média & contenus", "capitaliser sur la couverture presse + production de contenus live"),
        ],
        "site": "https://big.bpifrance.fr/",
        "highlight": "Grande couverture médiatique (TV, presse, digital)",
    },
    {
        "section": "fr",
        "slug": "paris-economic-forum",
        "title": "UN ÉVÉNEMENT CONÇU POUR LES DIRIGEANTS VISIONNAIRES ET DÉCIDEURS DE 1ER PLAN",
        "name": "Paris Economic Forum (ex Hub Forum)",
        "date": "1er au 2 décembre 2026",
        "lieu": "Paris",
        "audience": "CEOs de grands groupes et scale-ups, ministres et décideurs publics, investisseurs et acteurs du capital-risque, experts économiques et think tanks, médias économiques et influenceurs.",
        "taille": "300+ participants.",
        "format": "Keynotes, tables rondes, débats — format hybride influence + contenu + visibilité.",
        "infos": "Organisé par Hub Institute. Sous le haut patronage du Président de la République Emmanuel Macron. Forte dimension internationale.",
        "speakers": "Clara Chappaz (ambassadrice IA), Philippe d'Ornano (Sisley), Benoit Derigny (ManpowerGroup), Nicolas Dufourcq (Bpifrance), Enrique Martinez (Fnac-Darty).",
        "interets": [
            "Audience sélectionnée, très qualifiée et internationale",
            "Patronage présidentiel — légitimité institutionnelle",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque européenne pleinement intégrée aux cercles de décision économiques et politiques, capable de connecter dirigeants, fondateurs et pouvoirs publics autour des grandes transformations de l'économie.",
        "activations": [
            ("Prendre la parole en keynote ou session plénière", "Intervention d'un dirigeant CA sur les grandes transformations économiques et financières"),
            ("Valoriser la présence via contenus digitaux et diffusion du forum", "Renforcement de la marque sur transformation économique et innovation"),
        ],
        "site": "https://www.pariseconomicforum.com/",
        "highlight": "Sous haut patronage du Président de la République",
    },
    {
        "section": "fr",
        "slug": "adopt-ai",
        "title": "LE GRAND RENDEZ-VOUS EUROPÉEN DÉDIÉ À L'IA",
        "name": "Adopt AI by Artefact",
        "date": "3 au 4 décembre 2026",
        "lieu": "Grand Palais, Paris",
        "audience": "Dirigeants (C-level), décideurs data/IA, responsables innovation, grands groupes, scale-ups tech.",
        "taille": "20 000+ participants — audience ultra qualifiée, orientée décideurs.",
        "format": "Keynotes, retours d'expérience, cas clients, workshops, networking, stands démos.",
        "infos": "Organisé par le cabinet de conseil Artefact. Positionné comme le « Davos de l'IA ». Olivier Gavalda speaker en 2025. Partenaires sponsors : Société Générale, BPCE.",
        "speakers": "Olivier Gavalda (CA) en 2025.",
        "interets": [
            "Créer des opportunités de collaboration avec acteurs tech et data",
            "Positionnement « Davos de l'IA »",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une institution financière qui industrialise l'IA à grande échelle.",
        "activations": [
            ("Networking stratégique", "rencontres ciblées avec décideurs IA / innovation"),
            ("Keynote premium (niveau C-level)", "capitaliser sur la prise de parole type Olivier Gavalda"),
            ("Sponsoring du déjeuner écosystème", None),
        ],
        "site": "https://adoptai.artefact.com/",
        "highlight": "« Davos de l'IA » — concurrents sponsors : SocGen, BPCE",
    },
    {
        "section": "fr",
        "slug": "la-ref",
        "title": "LA RENCONTRE DES ENTREPRENEURS DE FRANCE",
        "name": "La REF (MEDEF)",
        "date": "26 au 27 août 2026",
        "lieu": "Roland Garros, Paris",
        "audience": "Dirigeants d'entreprises, décideurs publics, politiques, institutions, fédérations, médias.",
        "taille": "13 000+ participants — audience ultra qualifiée, orientée dirigeants.",
        "format": "Keynotes, débats, tables rondes, interviews, networking, village partenaires.",
        "infos": "Organisé par le MEDEF. Le rendez-vous économique et politique de la rentrée en France. Boursorama couvrait l'événement en 2025.",
        "speakers": "Forte présence personnalités politiques et dirigeants majeurs.",
        "interets": [
            "Couverture média massive — +25 médias partenaires en 2025",
            "Forte présence personnalités politiques et dirigeants majeurs",
        ],
        "positionnement": "Positionner le Crédit Agricole comme un acteur clé de la souveraineté économique et des transformations des territoires, capable de faire le lien entre économie réelle, innovation et politiques publiques.",
        "activations": [
            ("Prise de parole stratégique (niveau COMEX)", "souveraineté économique, financement des entreprises, IA, transition"),
            ("Présence visible dans le village partenaires", "stand orienté influence + rencontres institutionnelles"),
            ("Rencontres ciblées (public / privé)", None),
            ("Activation RP & média", "interviews, tribunes"),
            ("Production de contenus", None),
        ],
        "site": "https://laref.org/",
        "highlight": "Rendez-vous économique et politique de la rentrée",
    },
    {
        "section": "fr",
        "slug": "bank-acceleration",
        "title": "LES FORCES QUI TRANSFORMENT L'INDUSTRIE BANCAIRE",
        "name": "Bank Acceleration (L'Agefi)",
        "date": "6 octobre 2026",
        "lieu": "Palais Brongniart, Paris",
        "audience": "Décideurs bancaires, dirigeants financiers, experts innovation, fintechs, régulateurs, acteurs cybersécurité et blockchain.",
        "taille": "1 000+ participants.",
        "format": "Conférences, keynotes, tables rondes, retours d'expérience, débats stratégiques.",
        "infos": "Organisé par L'Agefi. Thématiques : agents IA, nouveaux services bancaires, agence de demain, euro numérique, blockchain, cybersécurité. Peu de partenaires aujourd'hui.",
        "speakers": "À venir 2026.",
        "interets": [
            "Prendre part aux débats structurants du secteur (IA, monnaie digitale, infrastructure bancaire)",
            "Renforcer la crédibilité auprès des pairs bancaires et régulateurs",
            "Anticiper les ruptures technologiques du secteur financier",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque qui anticipe et construit les modèles bancaires de demain, à la croisée de l'IA, de la régulation et de l'innovation technologique.",
        "activations": [
            ("Prise de parole stratégique (C-level / direction innovation)", "« La banque augmentée : entre IA, souveraineté et nouveaux usages »"),
            ("Intervention sur cas concrets", "agents IA, automatisation bancaire, transformation des agences"),
            ("Contenus experts & décryptages", "thought leadership sur les transformations du secteur"),
            ("Networking institutionnel", "échanges avec régulateurs, banques et acteurs de place"),
        ],
        "site": "https://bankacceleration.evenements.agefi.fr/fr/",
        "highlight": "Peu de partenaires aujourd'hui — fenêtre de positionnement",
    },
    {
        "section": "fr",
        "slug": "hubtalk-banking-assurance",
        "title": "FAIRE DE L'IA UN MOTEUR D'AGILITÉ DANS LE SECTEUR",
        "name": "HubTalk Banking & Assurance",
        "date": "5 novembre 2026",
        "lieu": "Deskeo Champerret, Paris",
        "audience": "Dirigeants banque & assurance, responsables innovation, data/IA, digital, expérience client, risk & compliance, fintechs et insurtechs.",
        "taille": "500+ participants — audience qualifiée, très décisionnelle.",
        "format": "Keynotes, témoignages dirigeants, sessions d'échanges en petits groupes.",
        "infos": "Organisé par Hub Institute. Thématiques : agilité des organisations, industrialisation de l'IA, personnalisation client, cybersécurité, AI Act.",
        "speakers": "À venir 2026.",
        "interets": [
            "Travailler la crédibilité sur les sujets confiance, sécurité et conformité",
            "Se connecter aux enjeux opérationnels banque & assurance",
            "Identifier des leviers d'industrialisation rapide de l'IA",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque qui industrialise l'IA de manière responsable, en conciliant performance opérationnelle, personnalisation client et exigences de confiance.",
        "activations": [
            ("Témoignage dirigeant / retour d'expérience", "transformation IA dans les métiers banque/assurance"),
            ("Networking expert", "échanges avec décideurs métiers et innovation"),
        ],
        "site": "https://www.hubinstitute.com/hubtalk/banking-assurance",
        "highlight": "Audience qualifiée, très décisionnelle (500+)",
    },
    {
        "section": "fr",
        "slug": "investir-day",
        "title": "LE RENDEZ-VOUS DE L'INVESTISSEMENT NOUVELLE GÉNÉRATION",
        "name": "Investir Day",
        "date": "24 novembre 2026",
        "lieu": "Carrousel du Louvre, Paris",
        "audience": "Investisseurs particuliers, professionnels de la finance, gestionnaires de patrimoine, fintechs, banques, sociétés de gestion, acteurs crypto et immobilier.",
        "taille": "8 000+ participants — audience mixte grand public + experts.",
        "format": "Conférences, masterclasses, keynotes, ateliers pédagogiques, networking, espaces exposants.",
        "infos": "Organisé par Groupe Les Echos-Le Parisien × Hopscotch. Thématiques larges : crypto, fintech, crowdfunding, investissement responsable, capital investissement, immobilier, fiscalité, bourse, gestion de patrimoine.",
        "speakers": "À venir 2026.",
        "interets": [
            "Positionnement hybride : expertise + démocratisation",
            "Capter les évolutions des usages d'investissement (crypto, fintech…)",
            "Valoriser l'accompagnement patrimonial et la gestion de l'épargne",
            "Accroître la visibilité dans un écosystème grand public à forte audience média",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque de référence sur l'accompagnement patrimonial global, capable de guider les investisseurs dans la complexité des nouveaux marchés financiers.",
        "activations": [
            ("Keynote pédagogie investissement", None),
            ("Stand conseil / expertise", "accompagnement personnalisé sur les stratégies d'investissement"),
            ("Contenus éducatifs média", "formats courts pédagogiques (épargne, marchés, IA financière, crypto)"),
        ],
        "site": "https://www.investirday.fr/",
        "highlight": "Audience hybride grand public + experts (8 000+)",
    },
    # --- EUROPE ---
    {
        "section": "eu",
        "slug": "bits-and-pretzels",
        "title": "LA CONFÉRENCE INTERNATIONALE DE FONDATEURS",
        "name": "Bits & Pretzels",
        "date": "28 au 30 septembre 2026",
        "lieu": "Munich, Allemagne",
        "audience": "Fondateurs de startups, scale-ups, investisseurs, VCs, corporate innovation, acteurs tech européens et internationaux.",
        "taille": "7 500+ participants — écosystème startup européen à forte dimension internationale.",
        "format": "Keynotes, panels, pitchs startups, networking intensif, side events, rencontres investisseurs.",
        "infos": "Organisé par Startup Events GmbH. Festival positionné comme un « Oktoberfest du business ».",
        "speakers": "Max Junestrand (Legora), Mirko Novakovic (Dash0), Jeannette zu Fürstenberg (General Catalyst), Ben Fletcher (Accel), Ritika Pai (Iconiq).",
        "interets": [
            "Renforcer la visibilité du Crédit Agricole à l'échelle européenne",
            "Accéder à un dealflow international (scale-ups, early-stage, VCs)",
            "Développer des opportunités de partenariats hors marché français",
            "Positionner la banque dans les réseaux d'innovation européens",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque européenne ouverte sur les écosystèmes internationaux, capable d'accompagner la croissance et l'expansion des scale-ups en Europe et à l'international.",
        "activations": [
            ("Présence networking forte (C-level / innovation)", "dîner ou soirée avec VCs et fondateurs européens (notamment French Tech)"),
            ("Prise de parole internationale", "financement scale-ups, expansion européenne, innovation bancaire fondée sur l'humain"),
            ("Participer au matchmaking", "rencontres partenaires (fonds, IA, fintech internationales, French Tech Berlin…)"),
            ("Contenus social media & brand awareness", None),
        ],
        "site": "https://www.bitsandpretzels.com/",
        "highlight": "Audience très internationale + forte concentration VC",
    },
    {
        "section": "eu",
        "slug": "gitex-europe",
        "title": "LE SALON MONDIAL DE LA TECH EN EUROPE",
        "name": "GITEX Europe",
        "date": "30 juin au 1er juillet 2026",
        "lieu": "Berlin, Allemagne",
        "audience": "Décideurs tech, dirigeants grands groupes, gouvernements, startups, scale-ups, investisseurs, experts IA, cybersécurité et cloud.",
        "taille": "60 000+ participants — événement tech mondial majeur.",
        "format": "Global tech expo, conférences, keynotes, démonstrations technologiques, zones startups, networking international.",
        "infos": "Version européenne de la franchise mondiale GITEX. Focus : IA, cybersécurité, cloud, data, infrastructures numériques, deeptech.",
        "speakers": "Maya Noel (France Digitale), Kazuhito Hadano (Sony Ventures), Ryan Fouty (Perplexity), Alberto Bacchiega (European Commission), Yannick Marin Isambert (Airbus).",
        "interets": [
            "Renforcer la crédibilité sur IA, cybersécurité et infrastructures digitales",
            "Identifier des partenaires technologiques stratégiques à grande échelle",
            "Accès à un écosystème global (Europe, Middle East, US, Asie)",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque européenne connectée aux technologies mondiales, capable d'intégrer et de sécuriser les innovations IA et cyber à grande échelle.",
        "activations": [
            ("Prise de parole internationale (C-level)", "IA, cybersécurité, souveraineté technologique, infrastructure bancaire"),
            ("Présence sur zone innovation / expo", "démonstration de cas d'usage IA / data / sécurité"),
            ("Participer aux side events", "dîner, cocktail (organisés par SAP, Microsoft, AWS…)"),
            ("Participer aux Executive Connect", "programme sur invitation — dirigeants ↔ fournisseurs d'IA"),
        ],
        "site": "https://www.gitexeurope.com/",
        "highlight": "Accès écosystème global (Europe + Middle East + US + Asie)",
    },
    {
        "section": "eu",
        "slug": "slush",
        "title": "L'ÉVÉNEMENT LE PLUS CENTRÉ SUR LES FONDATEURS — LE PLUS GRAND RASSEMBLEMENT DE CAPITAL-RISQUE",
        "name": "Slush",
        "date": "18 au 19 novembre 2026",
        "lieu": "Helsinki, Finlande",
        "audience": "Fondateurs de startups early stage à scale-ups, fonds d'investissement internationaux, corporate venture.",
        "taille": "12 000+ participants — très forte concentration VC.",
        "format": "Keynotes, pitching sessions / startup matchmaking, 1to1 meetings, side events, startup village.",
        "infos": "Organisé par Slush (association). Événement extrêmement « founder-first » — positionnement rare en Europe. Networking ultra ciblé : deals, fundraising, co-investissements.",
        "speakers": "Anton Osika (Lovable), Lucy Liu (Airwallex), Markus Villig (Bolt), Marc Lemaître (European Commission), Tim Zheng (Apollo.io), Eileen O'Mara (Stripe).",
        "interets": [
            "Détection de tendances : IA, climate tech, fintech, deeptech",
            "Accès direct à des startups en levée de fonds (early + growth)",
            "Visibilité auprès des VC internationaux",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque européenne connectée aux écosystèmes technologiques mondiaux, capable de financer, structurer et sécuriser la croissance des startups et scale-ups dans l'IA et la fintech.",
        "activations": [
            ("Prendre la parole sur une table ronde VC & founders", "format très orienté terrain, logique de partage d'expérience"),
            ("Organiser un side event référencé par l'événement", "ex. Relation banques / fonds / startups dans les tours de financement"),
            ("Contenus social media & brand awareness", None),
        ],
        "site": "https://slush.org/",
        "highlight": "Founder-first — positionnement rare en Europe",
    },
    {
        "section": "eu",
        "slug": "wave-by-vento",
        "title": "L'UNE DES CONFÉRENCES TECHNOLOGIQUES LES PLUS INFLUENTES D'ITALIE",
        "name": "Wave by Vento (ex Italian Tech Week)",
        "date": "7 au 9 octobre 2026",
        "lieu": "Turin, Italie",
        "audience": "Fondateurs, fonds de capital-risque internationaux, corporate venture capital, grands groupes tech et infrastructure (cloud, IA, data, fintech), acteurs publics et écosystèmes innovation européens, médias tech.",
        "taille": "15 000+ participants — 1 500 startups et +1 500 investisseurs présents.",
        "format": "Keynotes, tables rondes, 1to1 (≈ 4 500 meetings), zones de démos, podcast live et contenus éditoriaux.",
        "infos": "Organisé par Vento Ventures. Anciennement Italian Tech Week, devenu Wave by Vento (rebranding international).",
        "speakers": "John Elkann (Exor, Stellantis, Ferrari), Dario Amodei (Anthropic), Anas Biad (Sequoia), Anne Osdoit (Moon Surgical), Éléonore Crespo (Pigment), Joe Tsai (Alibaba).",
        "interets": [
            "Opportunité de créer des partenariats VC / corporate / tech à l'échelle européenne",
            "Renforcement de la visibilité auprès des fonds et corporate venture internationaux",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque européenne connectée aux écosystèmes technologiques mondiaux, capable de dialoguer avec les grandes plateformes, les investisseurs et les startups globales.",
        "activations": [
            ("Organiser des meetings multi-cibles (écosystème élargi)", "activation business et stratégie, environnement très international et hybride"),
            ("Sponsoriser la Night Summit", "événements dans toute la ville — toucher le grand public hors site principal"),
            ("Rejoindre le programme des ambassadeurs", "accès à des formats privés (VIP networking, introductions ciblées)"),
        ],
        "site": "https://wavebyvento.com/",
        "highlight": "Rebranding international 2026 — 4 500 meetings 1to1",
    },
    {
        "section": "eu",
        "slug": "web-summit",
        "title": "LE SALON MONDIAL DE LA TECH À LISBONNE",
        "name": "Web Summit",
        "date": "9 au 12 novembre 2026",
        "lieu": "Lisbonne, Portugal",
        "audience": "Décideurs tech, dirigeants grands groupes, gouvernements, startups, scale-ups, investisseurs, médias internationaux et leaders d'opinion tech, acteurs de l'écosystème (incubateurs, accélérateurs, hubs).",
        "taille": "70 000+ participants — événement tech mondial.",
        "format": "Keynotes, tables rondes multi-thématiques, startup pitch competitions, 1to1 meetings, village partenaires.",
        "infos": "Mix entre branding, business development et dealflow. Forte présence finance et fintech : Visa, Capital Numbers, Ankara, Toptal, Globant, Worldline, Payabl., Spendbase, TransactionLink.",
        "speakers": "Alex Schultz (Meta), Khaby Lame, Toto Wolff (Mercedes F1), Cristiano Amon (Qualcomm), A.G. Sulzberger (NYT).",
        "interets": [
            "Très forte densité de side events privés et corporate activations",
            "Visibilité mondiale auprès d'un écosystème tech élargi (au-delà du VC pur)",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque européenne connectée aux écosystèmes technologiques mondiaux, capable de dialoguer avec les grandes plateformes, les investisseurs et les startups globales.",
        "activations": [
            ("Prendre la parole sur une table ronde avec une fintech européenne", "rôle des banques dans l'accompagnement des scale-ups globales"),
            ("Participer au side event de Mastercard « Fintech & Impact »", None),
            ("Organiser des meetings ciblés (VC, scale-ups et corporate tech)", "générer du dealflow qualifié, renforcer partenariats stratégiques"),
        ],
        "site": "https://websummit.com/",
        "highlight": "Très forte densité de side events privés et corporate activations",
    },
    # --- INFLUENCE ---
    {
        "section": "influence",
        "slug": "royaumont",
        "title": "LE CERCLE D'INFLUENCE DES DÉCIDEURS ÉCONOMIQUES, POLITIQUES ET INTELLECTUELS",
        "name": "Les Entretiens Royaumont",
        "date": "Édition 2026 (dates à confirmer — généralement automne)",
        "lieu": "Abbaye de Royaumont",
        "audience": "Dirigeants de grandes entreprises françaises et européennes, banquiers et acteurs financiers institutionnels, décideurs publics et hauts fonctionnaires, intellectuels, chercheurs, économistes, journalistes et éditorialistes influents.",
        "taille": "Format très restreint et sélectif — cercle fermé.",
        "format": "Tables rondes de haut niveau (économie, géopolitique, société), débats fermés entre dirigeants et experts, dîners et networking informels.",
        "infos": "Positionnement historiquement très institutionnel et élitiste. BNP Paribas est partenaire.",
        "speakers": "Liste confidentielle.",
        "interets": [
            "Accès aux réflexions structurantes sur les transformations économiques et géopolitiques",
            "Peu d'activation visible — logique de discrétion et de légitimité",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque systémique européenne pleinement intégrée aux cercles de réflexion et de décision économiques et politiques, capable de contribuer aux grands débats structurants sur la transformation des modèles économiques, financiers et sociétaux.",
        "activations": [
            ("Intégrer le cercle des partenaires institutionnels", "objectif d'inscription du Crédit Agricole dans le cercle fermé des partenaires"),
            ("Participer aux dîners et sessions fermées de haut niveau", "accès aux formats les plus exclusifs (dîners, tables rondes restreintes, échanges off)"),
            ("Prendre part aux tables rondes stratégiques", "transformations économiques, financières ou géopolitiques"),
        ],
        "site": "https://www.lesentretiens.com/",
        "highlight": "Cercle fermé — BNP Paribas y est déjà partenaire",
    },
    {
        "section": "influence",
        "slug": "cercle-giverny",
        "title": "LE RENDEZ-VOUS DES ENTREPRISES DURABLES ET DE LA RSE STRATÉGIQUE",
        "name": "Le Cercle de Giverny",
        "date": "4 septembre 2026",
        "lieu": "Musée des Impressionnistes, Giverny",
        "audience": "Dirigeants de grandes entreprises (CAC 40, ETI, multinationales), banques et acteurs financiers institutionnels, décideurs publics, experts RSE, climat, énergie, biodiversité, ONG, chercheurs.",
        "taille": "1 000+ participants — événement très sélectif et qualifié, cercle de décideurs.",
        "format": "Tables rondes, keynotes, networking. Publication de propositions annuelles issues des travaux du Cercle.",
        "infos": "Fort ancrage institutionnel (haut patronage du ministère de l'Économie et des Finances). BNP Paribas et la Caisse des Dépôts sont partenaires.",
        "speakers": "Liste 2026 à venir.",
        "interets": [
            "Accéder aux décideurs ESG des grands groupes et aux directions RSE / stratégie",
            "S'intégrer aux cercles de décision RSE et climat des grandes entreprises françaises et européennes",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque européenne systémique pleinement intégrée aux cercles de décision de la transition, tout en jouant un rôle d'acteur clé dans la convergence entre finance, industrie et politiques publiques.",
        "activations": [
            ("Participer aux tables rondes RSE, climat et finance durable", "transformation des modèles économiques face à l'urgence climatique"),
            ("S'inscrire dans les dynamiques de travail du Cercle (groupes de propositions)", "contribution aux travaux annuels produisant des propositions concrètes"),
        ],
        "site": "https://cercle-giverny.fr/",
        "highlight": "Haut patronage du ministère de l'Économie — BNPP & CDC partenaires",
    },
    {
        "section": "influence",
        "slug": "matins-hec",
        "title": "LE RENDEZ-VOUS INTIMISTE DES DÉCIDEURS ÉCONOMIQUES ET POLITIQUES",
        "name": "Les Matins HEC",
        "date": "Sessions tout au long de l'année 2026",
        "lieu": "HEC Paris et lieux partenaires à Paris (ex : Place Vendôme, salons privés)",
        "audience": "Alumni HEC et grand public (diffusion social media).",
        "taille": "150 à 200 invités par session.",
        "format": "Interview animée par un journaliste, lors d'un petit-déjeuner.",
        "infos": "Format historique de la communauté HEC, relancé comme un cercle de réflexion régulier. Exemple récent : Marie-Anne Barbat-Layani (Présidente AMF). Partenariat éditorial avec Challenges.",
        "speakers": "Format invité unique par session.",
        "interets": [
            "Lien direct avec les futurs leaders économiques de demain",
            "Opportunité de contribuer aux débats structurants sur régulation financière, innovation bancaire et stabilité du système économique",
        ],
        "positionnement": "Positionner le Crédit Agricole en lien direct avec les futurs décideurs économiques de demain, et capable de contribuer aux débats structurants sur les grandes transformations du système financier et de l'économie.",
        "activations": [
            ("Participer en tant qu'invité intervenant (CEO / direction générale / affaires publiques)", "intervention sur les grands enjeux de transformation du secteur bancaire et financier"),
            ("Accéder au cercle d'invitation régulier des décideurs", "influence continue"),
        ],
        "site": "https://hecstories.fr/fr/category/editos/matin-hec/",
        "highlight": "Lien direct avec les futurs leaders économiques",
    },
    {
        "section": "influence",
        "slug": "polytechnique-ax",
        "title": "LE RÉSEAU D'INFLUENCE DES INGÉNIEURS ET DÉCIDEURS DE L'INNOVATION",
        "name": "Rencontres Alumni Polytechnique (AX)",
        "date": "Programmation continue 2026",
        "lieu": "AX — Association des anciens élèves de l'École polytechnique / Paris et lieux partenaires",
        "audience": "Alumni Polytechnique (ingénieurs, chercheurs, entrepreneurs), fondateurs de startups deeptech, IA, cybersécurité, quantique.",
        "taille": "50 à 300 participants selon les événements.",
        "format": "Interview classique ou dîner networking alumni.",
        "infos": "Connexion forte entre recherche scientifique, innovation et pouvoir économique.",
        "speakers": "Format alumni — variable selon sessions.",
        "interets": [
            "Construction d'une relation long terme avec les futurs décideurs économiques et industriels européens",
            "Accès direct à un vivier d'ingénieurs, entrepreneurs et décideurs technologiques",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque européenne connectée aux réseaux d'excellence scientifique et technologique, en lien direct avec les futurs décideurs économiques et industriels de demain, capable d'accompagner la transformation des innovations deeptech en projets économiques et industriels structurants.",
        "activations": [
            ("Prendre part aux conférences et tables rondes thématiques", "enjeux d'innovation technologique et de financement de la deeptech"),
            ("Participer aux dîners et formats alumni à forte valeur relationnelle", "networking très qualifié avec ingénieurs, entrepreneurs et dirigeants industriels"),
        ],
        "site": "https://ax.polytechnique.org/fr/agenda",
        "highlight": "Réseau d'excellence scientifique — vivier deeptech",
    },
    {
        "section": "influence",
        "slug": "challenges-100",
        "title": "LE CLASSEMENT ET L'ÉVÉNEMENT — LES 100 STARTUPS OÙ INVESTIR",
        "name": "100 Startups Challenges",
        "date": "Édition 2026 (publication annuelle — généralement en mars)",
        "lieu": "Événement de reveal à Paris",
        "audience": "Fondateurs de startups françaises, investisseurs grands groupes, décideurs économiques et médias spécialisés.",
        "taille": "100 startups sélectionnées chaque année. Forte audience B2B via Challenges. Large diffusion auprès des professionnels tech et finance.",
        "format": "Publication d'un classement éditorial de référence, pitchs et rencontres entre startups et investisseurs, sessions de networking, valorisation médiatique via Challenges.",
        "infos": "Alumni du classement devenus leaders européens et mondiaux : Doctolib, Back Market, Qonto…",
        "speakers": "Reveal annuel — speakers variables.",
        "interets": [
            "Renforcement du rôle du Crédit Agricole dans le financement de l'innovation en France",
            "Outil de veille stratégique pour anticiper les futures licornes",
        ],
        "positionnement": "Positionner le Crédit Agricole comme une banque européenne ancrée dans le financement de la nouvelle génération d'entrepreneurs, capable d'accompagner les startups les plus prometteuses dès leurs premières phases de croissance.",
        "activations": [
            ("Faire partie du jury de sélection", "intégration au comité d'évaluation des 100 startups sélectionnées"),
            ("Prendre la parole en tant que sponsor lors du reveal (keynote)", "enjeux de financement de l'innovation et de passage à l'échelle"),
            ("Proposer une dotation aux lauréats", "prix ou accompagnement dédié (financement, mentoring, accès réseau)"),
        ],
        "site": "https://www.challenges.fr/classements/start-up/",
        "highlight": "Alumni : Doctolib, Back Market, Qonto…",
    },
]
